name: mampfmonitor
description: Eine Ernährungstagebuch-App für Kinder.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
